# Generated by Django 5.2.3 on 2025-07-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
